server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123

jwt:
  secret: "siersi"
  expiration: 7 #day

mybatis-flex:
  global-config:
    normal-value-of-logic-delete: 1
    deleted-value-of-logic-delete: 0
    logic-delete-column: valid